PODS-9541 - Add logic to disallow the adding of a company without a company name
hmrc/pensions-scheme-migration-frontend pull request #231
Opened 2024-08-21 09:45 UTC by LauraToddCodes

2024-08-22 09:27 UTC, jamdade-sharad submitted a review, later dismissed
lgtm

2024-08-22 09:28 UTC, PavelVjalicin requested changes

2024-08-22 09:28 UTC, PavelVjalicin commented on test/controllers/trustees/company/SpokeTaskListControllerSpec.scala
> +      verify(mockRenderer, times(1)).render(templateCaptor.capture(), jsonCaptor.capture())(any())
If you look at capture function comments, it mentions how capturing mocked values makes no sense.
Instead with your mock you want to mock only this specific value that you are comparing to.

Example:
when(mockRenderer.render(ArgumentMatchers.eq(templateToBeRendered))).thenReturn(???)

This will ensure that the template will be expected template, otherwise the mock will fail and return null pointer exception.

The above will work the same as this code, but more efficiently.

I just dealt with this on MPS where the above was causing flakey test, while used with futures.

2024-08-22 09:28 UTC, PavelVjalicin commented on test/controllers/establishers/company/SpokeTaskListControllerSpec.scala
> +      verify(mockRenderer, times(1)).render(templateCaptor.capture(), jsonCaptor.capture())(any())
Same comment as below

2024-08-23 13:35 UTC, PavelVjalicin approved these changes

2024-08-23 13:39 UTC, merged