Pods 9735
hmrc/pensions-scheme-migration-frontend pull request #235
Opened 2024-08-30 15:49 UTC by PavelVjalicin

2024-09-09 13:32 UTC, jamdade-sharad commented on app/controllers/establishers/AlreadyDeletedController.scala
> +              case None => "Scheme"
in case None => "Scheme" may be behave incorrect if existingSchemeName not found, need to double check return val

2024-09-09 13:34 UTC, jamdade-sharad commented on app/helpers/cya/CYAHelperForTwirl.scala
> +
Above commented code can be removed if not in use

2024-09-09 13:35 UTC, jamdade-sharad commented on app/helpers/cya/establishers/company/EstablisherCompanyAddressCYAHelper.scala
>   *
Needs to correct copyright year as 2024

2024-09-10 08:13 UTC, jamdade-sharad requested changes
Review comments added

2024-09-10 08:48 UTC, PavelVjalicin commented on app/helpers/cya/CYAHelperForTwirl.scala
> +
This is temporary for twirl migration. This will be removed when we remove nunujucks, lets leave it in for now.

2024-09-10 08:50 UTC, jamdade-sharad commented on app/helpers/cya/CYAHelperForTwirl.scala
> +
ok

2024-09-10 08:54 UTC, PavelVjalicin commented on app/controllers/establishers/AlreadyDeletedController.scala
> +              case None => "Scheme"
schemeName is now optional for the twirl template. Only shows return link if available.

2024-09-10 08:55 UTC, PavelVjalicin commented on app/helpers/cya/establishers/company/EstablisherCompanyAddressCYAHelper.scala
>   *
Updated copyright text.

2024-09-10 08:58 UTC, jamdade-sharad submitted a review, later dismissed
looks good

2024-09-10 09:47 UTC, jamdade-sharad approved these changes
lgtm

2024-09-10 10:00 UTC, merged