Pods 9712
hmrc/pensions-scheme-migration-frontend pull request #266
Opened 2024-10-03 10:27 UTC by PavelVjalicin

2024-10-03 10:43 UTC, PavelVjalicin commented on app/views/EmailView.scala.html
> +    @* @if(paragraphs) {
Commented out code.

2024-10-03 10:43 UTC, PavelVjalicin commented on app/views/HasReferenceValueView.scala.html
Empty file? Need to remove?

2024-10-03 10:43 UTC, PavelVjalicin commented on test/controllers/adviser/EnterEmailControllerSpec.scala
> +      contentAsString(result) must include(messages("messages__enterEmail_pageHeading", advisorName))
Rewrite this to use compare view function.

2024-10-03 10:43 UTC, PavelVjalicin commented on test/controllers/establishers/company/contact/EnterEmailControllerSpec.scala
> +      contentAsString(result) must include (formData)
should use compare function

2024-10-03 10:44 UTC, PavelVjalicin commented
Remove .njx files that were migrated.
Get a list of URL to test for this to testers and put the ticket into testing

2024-10-03 11:21 UTC, nonebula commented on app/views/HasReferenceValueView.scala.html
Removed.

2024-10-03 11:21 UTC, nonebula commented on app/views/EmailView.scala.html
> +    @* @if(paragraphs) {
Uncommented.

2024-10-07 12:19 UTC, jamdade-sharad requested changes
Remove commented code

2024-10-07 12:19 UTC, jamdade-sharad commented on test/controllers/establishers/company/director/details/DirectorEnterUTRControllerSpec.scala
> +
remove commented code if not required

2024-10-07 12:19 UTC, jamdade-sharad commented on test/controllers/establishers/individual/details/EstablisherEnterNINOControllerSpec.scala
> +//    )
Remove unused code

2024-10-07 12:19 UTC, jamdade-sharad commented on test/controllers/establishers/partnership/details/UTRControllerSpec.scala
Remove unused code

2024-10-07 12:19 UTC, jamdade-sharad commented on test/controllers/establishers/partnership/details/VATControllerSpec.scala
> +//    )
remove commented code

2024-10-07 12:19 UTC, jamdade-sharad commented on test/controllers/trustees/company/details/UTRControllerSpec.scala
> +//    )
remove commented code

2024-10-07 12:19 UTC, jamdade-sharad commented on test/controllers/trustees/company/details/VATControllerSpec.scala
remove commented code

2024-10-07 14:06 UTC, jamdade-sharad approved these changes

2024-10-08 09:25 UTC, merged