Pods 5548:Add Establisher contact details | Company
hmrc/pensions-scheme-migration-frontend pull request #45
Opened 2021-07-19 15:14 UTC by jigneshkumarpatel

2021-07-21 14:29 UTC, madhuranakate requested changes

2021-07-21 14:29 UTC, madhuranakate commented on app/controllers/establishers/company/contact/WhatYouWillNeedCompanyContactController.scala
> +              template = "establishers/company/contact/whatYouWillNeed.njk",
can this be put in a common place to be reused for trustee company contact?

2021-07-21 14:29 UTC, madhuranakate commented on app/identifiers/establishers/company/contact/EnterEmailId.scala
> +    "companyemail"
either use just "email" or change to camelCase

2021-07-21 14:29 UTC, madhuranakate commented on app/identifiers/establishers/company/contact/EnterPhoneId.scala
> +    "companyphone"
either use just "phone" or change to camelCase

2021-07-21 14:29 UTC, madhuranakate commented on test/utils/datacompletion/DataCompletionEstablishersSpec.scala
>    }
SpokeCreationServiceSpec needs new tests/updates for updated code

2021-07-21 22:01 UTC, jigneshkumarpatel commented on app/controllers/establishers/company/contact/WhatYouWillNeedCompanyContactController.scala
> +              template = "establishers/company/contact/whatYouWillNeed.njk",
Move the njk to establishers and added title on controller to have component use across module .

2021-07-21 22:01 UTC, jigneshkumarpatel commented on app/identifiers/establishers/company/contact/EnterEmailId.scala
> +    "companyemail"
updated to compnayEmail

2021-07-21 22:01 UTC, jigneshkumarpatel commented on app/identifiers/establishers/company/contact/EnterPhoneId.scala
> +    "companyphone"
updated to camelCase

2021-07-21 22:02 UTC, jigneshkumarpatel commented on test/utils/datacompletion/DataCompletionEstablishersSpec.scala
>    }
updated test class for Spokeservice

2021-07-22 07:48 UTC, madhuranakate approved these changes

2021-07-22 07:48 UTC, merged