Pods 5782
hmrc/pensions-scheme-migration-frontend pull request #78
Opened 2021-09-01 12:54 UTC by jigneshkumarpatel

2021-09-02 15:36 UTC, madhuranakate requested changes

2021-09-02 15:36 UTC, madhuranakate commented on app/identifiers/trustees/partnership/contact/EnterEmailId.scala
> +  def collectionPath(index: Int): JsPath =
is this used anywhere? we can get rid of the collectionPath if not used

2021-09-02 15:36 UTC, madhuranakate commented on app/identifiers/trustees/partnership/contact/EnterPhoneId.scala
> +  def collectionPath(index: Int): JsPath =
same here

2021-09-02 15:36 UTC, madhuranakate commented on app/helpers/cya/trustees/partnership/TrusteeContactDetailsCYAHelper.scala
> +}
Tests should be added for CYA helper, spoke creation and data completion

2021-09-03 10:09 UTC, grantrobson commented on app/helpers/SpokeCreationService.scala
>  //import helpers.spokes.establishers.partnership.{EstablisherPartnershipAddress, EstablisherPartnershipDetails, EstablisherPartnerDetails}
Commented line

2021-09-03 10:12 UTC, grantrobson approved these changes

2021-09-03 10:14 UTC, merged