Pods 5584
hmrc/pensions-scheme-migration-frontend pull request #86
Opened 2021-09-06 15:44 UTC by brownbonnie

2021-09-06 16:39 UTC, madhuranakate requested changes

2021-09-06 16:39 UTC, madhuranakate commented on app/identifiers/establishers/partnership/contact/EnterEmailId.scala
> +  def collectionPath(index: Int): JsPath =
collectionPath not required

2021-09-06 16:39 UTC, madhuranakate commented on app/identifiers/establishers/partnership/contact/EnterPhoneId.scala
> +  def collectionPath(index: Int): JsPath =
collectionPath not required

2021-09-06 16:39 UTC, madhuranakate commented on app/helpers/cya/establishers/partnership/EstablisherPartnershipContactDetailsCYAHelper.scala
> +}
Tests are missing for CYA helper, navigator and DataCompletion

2021-09-06 16:51 UTC, jigneshkumarpatel commented on app/identifiers/establishers/partnership/contact/EnterEmailId.scala
> +  def collectionPath(index: Int): JsPath =
remove collectionPath

2021-09-06 19:27 UTC, madhuranakate approved these changes

2021-09-06 19:28 UTC, merged

2021-09-09 09:27 UTC, brownbonnie commented on app/helpers/cya/establishers/partnership/EstablisherPartnershipContactDetailsCYAHelper.scala
> +}
Unit tests added